name: Static Blacklist Only (changes to blacklists not supported)

on:
    pull_request:
        branches:
            - master
        paths:
            - 'blacklists/*.json'
jobs:
    static-blacklist-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: JSON files syntax and URL validation
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
            - run: npm install
            - run: npm run static-bl-fail
